services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.common #! Needs to be properly defined 
      args:
        PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - .env

  product-service:
    build:
      context: ./services/product-service
      dockerfile: ../../Dockerfile.common #! Needs to be properly defined 
      args:
        PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./services/product-service:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - mongodb
    entrypoint: /bin/sh -c "sh /app/scripts/init-products.sh && npm run dev"

  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: ../../Dockerfile.common #! Needs to be properly defined 
      args:
        PORT: 3001
    ports:
      - "3001:3001"
    volumes:
      - ./services/auth-service:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - mongodb

  order-service:
    build:
      context: ./services/order-service
      dockerfile: ../../Dockerfile.common #! Needs to be properly defined 
      args:
        PORT: 3002
    ports:
      - "3002:3002"
    volumes:
      - ./services/order-service:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - ./mongo-data:/data/db
