FROM node:18-alpine AS build

WORKDIR /app

COPY package.json ./

RUN npm install

COPY index.html ./
COPY server.cjs ./
COPY src ./src
COPY vite.config.js ./

RUN if npm run | grep -q "^  build$"; then \
        npm run build; \
    else \
        echo "Build not necessary or development mode"; \
    fi

FROM node:18-alpine

WORKDIR /app

COPY package.json ./
RUN npm install --only=production

COPY --from=build /app/dist /app/dist

ARG PORT=3001
EXPOSE $PORT

CMD ["sh", "-c", "npm run start"]
