global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "auth-service"
    static_configs:
      - targets: ["host.docker.internal:3001"]

  - job_name: "product-service"
    static_configs:
      - targets: ["host.docker.internal:3000"]

  - job_name: "order-service"
    static_configs:
      - targets: ["host.docker.internal:3002"]

  - job_name: "mongodb"
    static_configs:
      - targets: ["mongodb-exporter:9216"]
